### ISSUE TITLE
Separate AI and Back-end

### ISSUE THREAD

**Issue by lunathanael** [lunathanael/clash-royale-rl#7]
This repo will be dedicated for the back-end of CR-RL, all actual AI implementation will be either in another repository or notebook. Instead of having a main branch for releases, we will move them to github releases and utilize PIP for deployment.
`pyproject.toml` needs to be setup.

**Comment by lunathanael** [comment]
#9 Is Part of this process

**Comment by OwenCochell** [comment]
I will be adding pyproject.toml soon, will create PR and reference this issue
